### PR TITLE
Adds Apache License to the repository

### PR DESCRIPTION
**Pull request by wilderrodrigues**
It's important to have a license for the dataset [DUT Anti-UAV] distributed via this repository.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
@zj5559 @wangdongdut 

I'm currently doing some research with Anti UAV datasets and can work only with datasets that contain a license. In my opinions, your dataset is quite good and should be made available to the research community in a broader way. Hence, I would like to know if it's possible to add the Apache License to it. Since your dataset is distributed via Google Drive and Baidu, with links in this repository, adding the license here should suffice.

Thanks in advance.

**Comment by zj5559** [comment]
Thanks for your advice, the license has been added:)

**Comment by wilderrodrigues** [comment]
Thank you very much on behalf of the whole community, @zj5559. I will close this PR as the license is already available.

**Comment by wilderrodrigues** [comment]
Hi again, @zj5559 .

Can I ask one last question? :) 

Q: were the images captured by Dalian University of Technology (and you) or you collected them from [e.g.] Flickr?

In the your paper it's mentioned that they were manually annotated, but nothing about how they were captured / collected.

Thanks again for your time.

**Pull request closed without merging**
